name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy
        run: |
          git config --global --add safe.directory /var/www/belajarCICD

          cd /var/www/belajarCICD

          git fetch origin
          git reset --hard origin/main

          composer install --no-dev --optimize-autoloader

          php artisan migrate --force

          php artisan optimize