name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd /var/www/belajarCICD

          git pull origin main

          composer install --no-dev --optimize-autoloader

          php artisan migrate --force

          php artisan optimize

          